insert into dolzhnost(`name`, `oklad`) value ('Администратор', 35000);
select * from dolzhnost;
insert into dolzhnost(`name`, `oklad`) value ('Директор', 40000);
select * from dolzhnost;
insert into dolzhnost(`name`, `oklad`) value ('IT-специалист', 30000);
select * from dolzhnost;
insert into dolzhnost(`name`, `oklad`) value ('Уборщик', 15000);
select * from dolzhnost;
insert into dolzhnost(`name`, `oklad`) value ('Консультант', 25000);
select * from dolzhnost;

insert into vid_komplekt(`name`) value ('Материнская плата');
select * from vid_komplekt;
insert into vid_komplekt(`name`) value ('Монитор');
select * from vid_komplekt;
insert into vid_komplekt(`name`) value ('Системный блок');
select * from vid_komplekt;

insert into komplekt(`marka`, `cena`) value ('Intel', 20000);
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('SATA', 30000);
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;
insert into komplekt(`marka`, `cena`) value ('', );
select * from komplekt;